### ISSUE TITLE
Test are not stable

### ISSUE THREAD

**Issue by kardapoltsev** [Ma27/rediscala#16]
There are a lot of hardcoded timeouts in tests and they are not stable (tests fail on slow environment like travis).
Also, what do you think about moving to scalatest instead of specs? I have some free time now for this project (:

**Comment by Ma27** [comment]
Yeah, the tests seem to be quite a mess. Way too much output that makes it hard to reason about, rather slow and so on... I tried to clean this up to get the build working on GitLab CI, but I gave up last summer due to time limitations, so any improvements there are welcome! :)

> Also, what do you think about moving to scalatest instead of specs

I mostly worked with `scalatest` (and except for this project nothing with `specs`), so :+1:

**Comment by kardapoltsev** [comment]
FYI I've started to work on it.

**Comment by Ma27** [comment]
Should be fixed by #17 :tada:
